package eject

import (
	"fmt"
	"sort"

	"github.com/posit-dev/ptd/lib/types"
)

type SecretReference struct {
	Name      string        `json:"name"`
	Purpose   string        `json:"purpose"`
	CreatedBy string        `json:"created_by"`
	Fields    []SecretField `json:"fields,omitempty"`
}

type SecretField struct {
	Name          string `json:"name"`
	Description   string `json:"description"`
	AutoGenerated bool   `json:"auto_generated"`
}

func EnumerateSecrets(target types.Target) []SecretReference {
	siteNames := sortedSiteNames(target.Sites())

	if target.CloudProvider() == types.Azure {
		return enumerateAzureSecrets(target.Name(), siteNames)
	}
	return enumerateAWSSecrets(target.Name(), siteNames)
}

func sortedSiteNames(sites map[string]types.SiteConfig) []string {
	names := make([]string, 0, len(sites))
	for name := range sites {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func enumerateAWSSecrets(workloadName string, siteNames []string) []SecretReference {
	var refs []SecretReference

	refs = append(refs, SecretReference{
		Name:      fmt.Sprintf("%s.posit.team", workloadName),
		Purpose:   "Workload infrastructure references (DB URL, FSx DNS, S3 buckets)",
		CreatedBy: "bootstrap + persistent step",
		Fields:    awsWorkloadSecretFields(),
	})

	for _, site := range siteNames {
		refs = append(refs, SecretReference{
			Name:      fmt.Sprintf("%s-%s.posit.team", workloadName, site),
			Purpose:   "Site configuration: database passwords, licenses, OIDC secrets, RSA keys",
			CreatedBy: "bootstrap (structure + auto-generated values), manual (licenses, OIDC, tokens)",
			Fields:    siteSecretFields(),
		})

		refs = append(refs, SecretReference{
			Name:      fmt.Sprintf("%s-%s.sessions.posit.team", workloadName, site),
			Purpose:   "Application session data, populated by Team Operator at runtime",
			CreatedBy: "bootstrap (empty), Team Operator (runtime)",
		})

		refs = append(refs, SecretReference{
			Name:      fmt.Sprintf("%s-%s-ssh-ppm-keys.posit.team", workloadName, site),
			Purpose:   "SSH private keys for Package Manager Git repository authentication",
			CreatedBy: "bootstrap (empty), manual (SSH keys per Git host)",
		})

		refs = append(refs, SecretReference{
			Name:      fmt.Sprintf("okta-oidc-client-creds.%s-%s.posit.team", workloadName, site),
			Purpose:   "Traefik forward auth OIDC credentials (only if OIDC auth is configured)",
			CreatedBy: "external (manual)",
			Fields: []SecretField{
				{Name: "oidcClientId", Description: "OIDC client ID"},
				{Name: "oidcClientSecret", Description: "OIDC client secret"},
				{Name: "signingSecret", Description: "Traefik forward auth signing secret"},
			},
		})
	}

	return refs
}

func enumerateAzureSecrets(workloadName string, siteNames []string) []SecretReference {
	var refs []SecretReference

	refs = append(refs, SecretReference{
		Name:      fmt.Sprintf("%s-main-db-fqdn", workloadName),
		Purpose:   "PostgreSQL server FQDN",
		CreatedBy: "persistent step",
	})

	fields := siteSecretFields()
	for _, site := range siteNames {
		for _, f := range fields {
			refs = append(refs, SecretReference{
				Name:      fmt.Sprintf("%s-%s", site, f.Name),
				Purpose:   f.Description,
				CreatedBy: createdByForField(f),
			})
		}
	}

	return refs
}

func createdByForField(f SecretField) string {
	if f.AutoGenerated {
		return "bootstrap (auto-generated)"
	}
	return "manual"
}

func awsWorkloadSecretFields() []SecretField {
	return []SecretField{
		{Name: "chronicle-bucket", Description: "S3 bucket for Chronicle audit logs", AutoGenerated: true},
		{Name: "fs-dns-name", Description: "FSx OpenZFS filesystem DNS name", AutoGenerated: true},
		{Name: "fs-root-volume-id", Description: "FSx root volume ID", AutoGenerated: true},
		{Name: "main-database-id", Description: "RDS instance identifier", AutoGenerated: true},
		{Name: "main-database-url", Description: "RDS connection URL", AutoGenerated: true},
		{Name: "packagemanager-bucket", Description: "S3 bucket for Package Manager packages", AutoGenerated: true},
	}
}

func siteSecretFields() []SecretField {
	return []SecretField{
		{Name: "dev-admin-token", Description: "Workbench admin API token"},
		{Name: "dev-client-secret", Description: "Workbench OIDC client secret"},
		{Name: "dev-db-password", Description: "Workbench database password", AutoGenerated: true},
		{Name: "dev-license", Description: "Workbench license key"},
		{Name: "dev-user-token", Description: "Workbench user API token"},
		{Name: "dev-chronicle-api-key", Description: "Workbench Chronicle API key"},
		{Name: "home-auth-map", Description: "Home service authentication mapping"},
		{Name: "keycloak-db-user", Description: "Keycloak database username", AutoGenerated: true},
		{Name: "keycloak-db-password", Description: "Keycloak database password", AutoGenerated: true},
		{Name: "pkg-db-password", Description: "Package Manager database password", AutoGenerated: true},
		{Name: "pkg-license", Description: "Package Manager license key"},
		{Name: "pkg-secret-key", Description: "Package Manager RSA secret key", AutoGenerated: true},
		{Name: "ppm-oidc-client-secret", Description: "Private Package Manager OIDC client secret"},
		{Name: "pub-client-secret", Description: "Connect OIDC client secret"},
		{Name: "pub-db-password", Description: "Connect database password", AutoGenerated: true},
		{Name: "pub-license", Description: "Connect license key"},
		{Name: "pub-secret-key", Description: "Connect RSA secret key", AutoGenerated: true},
		{Name: "pub-chronicle-api-key", Description: "Connect Chronicle API key"},
	}
}
