package eject

import (
	"testing"

	"github.com/posit-dev/ptd/lib/types"
	"github.com/posit-dev/ptd/lib/types/typestest"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func awsTarget(name string, sites map[string]types.SiteConfig) *typestest.MockTarget {
	mt := &typestest.MockTarget{}
	mt.On("Name").Return(name)
	mt.On("CloudProvider").Return(types.AWS)
	mt.On("Sites").Return(sites)
	return mt
}

func azureTarget(name string, sites map[string]types.SiteConfig) *typestest.MockTarget {
	mt := &typestest.MockTarget{}
	mt.On("Name").Return(name)
	mt.On("CloudProvider").Return(types.Azure)
	mt.On("Sites").Return(sites)
	return mt
}

func TestEnumerateSecrets_AWS_SingleSite(t *testing.T) {
	target := awsTarget("myworkload", map[string]types.SiteConfig{"main": {}})
	refs := EnumerateSecrets(target)

	// 1 workload + 4 per site (site, session, ssh-vault, oidc)
	require.Len(t, refs, 5)

	assert.Equal(t, "myworkload.posit.team", refs[0].Name)
	assert.Len(t, refs[0].Fields, 6)

	assert.Equal(t, "myworkload-main.posit.team", refs[1].Name)
	assert.Len(t, refs[1].Fields, 18)

	assert.Equal(t, "myworkload-main.sessions.posit.team", refs[2].Name)
	assert.Empty(t, refs[2].Fields)

	assert.Equal(t, "myworkload-main-ssh-ppm-keys.posit.team", refs[3].Name)

	assert.Equal(t, "okta-oidc-client-creds.myworkload-main.posit.team", refs[4].Name)
	assert.Len(t, refs[4].Fields, 3)
}

func TestEnumerateSecrets_AWS_MultipleSites(t *testing.T) {
	target := awsTarget("wl", map[string]types.SiteConfig{"main": {}, "secondary": {}})
	refs := EnumerateSecrets(target)

	// 1 workload + 4 per site × 2 sites = 9
	assert.Len(t, refs, 9)

	assert.Equal(t, "wl.posit.team", refs[0].Name)
	// Sites are sorted, so "main" comes before "secondary"
	assert.Equal(t, "wl-main.posit.team", refs[1].Name)
	assert.Equal(t, "wl-secondary.posit.team", refs[5].Name)
}

func TestEnumerateSecrets_AWS_NoSites(t *testing.T) {
	target := awsTarget("wl", map[string]types.SiteConfig{})
	refs := EnumerateSecrets(target)

	require.Len(t, refs, 1)
	assert.Equal(t, "wl.posit.team", refs[0].Name)
}

func TestEnumerateSecrets_Azure(t *testing.T) {
	target := azureTarget("myworkload", map[string]types.SiteConfig{"main": {}})
	refs := EnumerateSecrets(target)

	// 1 workload-level (db-fqdn) + 18 individual KV secrets per site
	assert.Len(t, refs, 19)

	assert.Equal(t, "myworkload-main-db-fqdn", refs[0].Name)
	assert.Equal(t, "main-dev-admin-token", refs[1].Name)
}

func TestSiteSecretFields_Count(t *testing.T) {
	fields := siteSecretFields()
	assert.Len(t, fields, 18)
}

func TestSiteSecretFields_AutoGeneratedFlags(t *testing.T) {
	fields := siteSecretFields()

	autoGenerated := map[string]bool{}
	for _, f := range fields {
		autoGenerated[f.Name] = f.AutoGenerated
	}

	assert.True(t, autoGenerated["dev-db-password"])
	assert.True(t, autoGenerated["keycloak-db-user"])
	assert.True(t, autoGenerated["keycloak-db-password"])
	assert.True(t, autoGenerated["pkg-db-password"])
	assert.True(t, autoGenerated["pkg-secret-key"])
	assert.True(t, autoGenerated["pub-db-password"])
	assert.True(t, autoGenerated["pub-secret-key"])

	assert.False(t, autoGenerated["dev-license"])
	assert.False(t, autoGenerated["pub-license"])
	assert.False(t, autoGenerated["pkg-license"])
	assert.False(t, autoGenerated["dev-client-secret"])
	assert.False(t, autoGenerated["pub-client-secret"])
	assert.False(t, autoGenerated["ppm-oidc-client-secret"])
}

func TestAWSWorkloadSecretFields_Count(t *testing.T) {
	fields := awsWorkloadSecretFields()
	assert.Len(t, fields, 6)

	for _, f := range fields {
		assert.True(t, f.AutoGenerated, "workload field %s should be auto-generated", f.Name)
	}
}

func TestEnumerateSecrets_Azure_MultipleSites(t *testing.T) {
	target := azureTarget("wl", map[string]types.SiteConfig{"main": {}, "secondary": {}})
	refs := EnumerateSecrets(target)

	// 1 workload-level + 18 per site × 2 sites = 37
	assert.Len(t, refs, 37)
}
