name: cmd

on:
  push:
    branches: [main]
    tags: [v*]
    paths: [cmd/**,lib/**,.github/workflows/cmd.yml,.github/actions/go-cache/**]

  pull_request:
    paths: [cmd/**,lib/**,.github/workflows/cmd.yml,.github/actions/go-cache/**]

  merge_group:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: extractions/setup-just@v2

      - uses: actions/setup-go@v5
        with:
          go-version-file: cmd/go.mod
          cache: false

      - uses: ./.github/actions/go-cache
        with:
          prefix: cmd-test

      - name: Test cmd
        run: just test-cmd

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: extractions/setup-just@v2

      - uses: actions/setup-go@v5
        with:
          go-version-file: cmd/go.mod
          cache: false

      - uses: ./.github/actions/go-cache
        with:
          prefix: cmd-build

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true

      - run: just cli

      - name: Archive cli
        uses: actions/upload-artifact@v4
        with:
          name: cli
          path: |
            dist/*
