name: lib

on:
  push:
    branches: [main]
    tags: [v*]
    paths: [lib/**,.github/workflows/lib.yml,.github/actions/go-cache/**]

  pull_request:
    paths: [lib/**,.github/workflows/lib.yml,.github/actions/go-cache/**]

  merge_group:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: extractions/setup-just@v2

      - uses: actions/setup-go@v5
        with:
          go-version-file: lib/go.mod
          cache: false

      - uses: ./.github/actions/go-cache
        with:
          prefix: lib-test

      - name: Test lib with coverage
        run: just test-lib
